### ISSUE TITLE
calendar bug ?

### ISSUE THREAD

**Issue by bugsounet** [MagicMirrorOrg/MagicMirror#3185]
Hi,

I use multi-calandar fetch on this default module (I use one instance)
And i see many fade out/in on each update

I use 4 calendars fetch so I have 4 fade out/in on updateDom (one for each calendar update)

It's not possible to work in async and merge all result and displaying ?
We will have only one fade out/in on update

honestly, I didn't look at the code, I don't know if it's possible (without breaking anything)

**Comment by Themaster312** [comment]
Same here

**Comment by bugsounet** [comment]
working arround ;)

**Comment by bugsounet** [comment]
@Themaster312 

 * What Raspberry Pi are you using ?
 * What's OS ?
