### ISSUE TITLE
Sleep mode 

### ISSUE THREAD

**Issue by riggo-coder** [MagicMirrorOrg/MagicMirror#3190]
Hello
I want to build my own smart mirror but i have one problem : i cant seem to find any way to deactivate or reactivate the raspberry pi and the  screen on a specific time, or wake it up at a specific time. For example i wake up at 7 am so i want it to activate at 6.55 am and stay on till 8 am
Thanks in advance

**Comment by riggo-coder** [comment]
Im quite new to this stuff so i dont really Know about the possibilities of the pi. Youre suggesting using an infrared sensor or find a way to trogger the tvs standby (for example just over time) and decrease the pis power consumption in the rest times and activate it by turning the power back on and having the tv wale up from rest morde roght? Can you also do sth similar mby with touch or sth? Or use a kamera for facial recognition? Eg me and my gf have diffrent scedules based on the recognition of the face

**Comment by khassel** [comment]
closing this because not related to mm core.
