### ISSUE TITLE
Feature - Custom Positions

### ISSUE THREAD

**Issue by Entropy159** [MagicMirrorOrg/MagicMirror#3212]
It is really annoying being stuck to the limiting default positions built into Magic Mirror. I would like to be able to set custom X and Y values for positioning modules.

**Comment by sdetweil** [comment]
You can use position absolute in the CSS and move your module anywhere you like, regardless of the position setting

**Comment by RahulSoni2532** [comment]
can you tell me where you want to move this 

![Screenshot 2023-10-10 224656](https://github.com/MichMich/MagicMirror/assets/146342894/9a77b1f3-d645-42b6-a855-a34d95dc38b3)

**Comment by RahulSoni2532** [comment]
i can work on this

**Comment by Entropy159** [comment]
Something interesting I've noticed is when I set an absolute position in the CSS, it's still relative to the area and gets messed up when other modules are toggled.

**Comment by khassel** [comment]
[this thread in the forum](https://forum.magicmirror.builders/topic/18069/multiple-modules-in-a-region) is an example how to override module positions.

I don't think we will change something concerning the module positions which will break existing mm instances.

**Comment by sdetweil** [comment]
@Entropy159   
> when I set an absolute position in the CSS, it's still relative to the area and gets messed up when other modules are toggled.

that is not correct... absolute is absolute. 

see here on how to use the developers console.
https://forum.magicmirror.builders/topic/14862/help-with-a-couple-css-issues?_=1696866322265

you can see and change the classes & styles live..

**Comment by Entropy159** [comment]
I have the CSS for the custom positioning, and it looks like this:
#module_14_MMM-TouchButton {
 top: 150px;
 left: 200px;
 position: absolute !important;
}
When I toggle the modules above it, the button moves to the right. I used the developer console, and it's applying the position correctly, but it still seems like it's relative.

**Comment by sdetweil** [comment]
yes, you are using the relative dimension tags..  top and left

use x and y

**Comment by Entropy159** [comment]
X and Y don't seem to do anything...
