### ISSUE TITLE
[newsfeed] Line break tags <br> should be replaced with spaces

### ISSUE THREAD

**Issue by d42ohpaz** [MagicMirrorOrg/MagicMirror#3235]
As an example, if you look at the RSS feed for lemmy.world, you'll notice that it uses line breaks. Because the newsfeed module seems to strip out HTML (rightfully so), it causes some of the text to be butted up against each other:

<img width="767" alt="Screenshot 2023-10-16 at 7 41 38 AM" src="https://github.com/MichMich/MagicMirror/assets/2528463/2c4d138e-6851-4808-a7dd-496608df5604">

Instead of stripping out \<br\> tags, it should replace them with a space (or non-breaking space (\&nbsp;)).

**Comment by bugsounet** [comment]
Hi, I don’t know if that’s really intended but according to the code it removes the `<...>` tag and replaces it with nothing.

see original code in `~/MagicMirror/modules/default/newsfeed/newsfeedfetcher.js` [line 56](https://github.com/MichMich/MagicMirror/blob/master/modules/default/newsfeed/newsfeedfetcher.js#L56)

Try to replace this line by `description = description.toString().replace(regex, " ");`

maybe it will be better in your case

**Comment by d42ohpaz** [comment]
@bugsounet Yes, that's exactly the solution needed.

**Comment by MichMich** [comment]
I've got absolutely no idea anymore. 🙈

**Comment by rejas** [comment]
> I've got absolutely no idea anymore. 🙈

well, 7 years is a long time... but maybe its really just trying to get rid of any html tags. which looks weird with <br> in the text. 

would just replacing those with an empty space " " look always okay I wonder?

@d42ohpaz do you want to code something (remove the regex and try to make a good looking description with some more options passed to the html-to-text library)?

**Comment by bugsounet** [comment]
I will inspect  html-to-text library options because actually, without regex, It display web links. I don't think it's raeally neded to display this

**Comment by rejas** [comment]
@d42ohpaz can you check if the latest develop branch fixes your problem?

**Comment by d42ohpaz** [comment]
> @d42ohpaz can you check if the latest develop branch fixes your problem?

Yup, looks fixed in latest develop branch. Thank you!
