### ISSUE TITLE
newsfeed discards feeds with a10:updated tag (includes solution)

### ISSUE THREAD

**Issue by kaennchenstruggle** [MagicMirrorOrg/MagicMirror#3238]
newsfeed discards feed items that use "a10:updated" tag instead of "pubdate" etc.

verify: https://www.tagblatt.de/Kreis%20T%C3%BCbingen.rss

```
[...]
const fetchNews = () => {
[...]
		parser.on("item", (item) => {
[...]
			const pubdate = item.pubdate || item.published || item.updated || item["dc:date"];
```

last line might be changed to
```
	                const pubdate = item.pubdate || item.published || item.updated || item["dc:date"] || item["a10:updated"];
```

Unfamiliar with PR, therefore included possible solution.

Thanks!

**Comment by khassel** [comment]
can confirm that the provided rss feed does not display any news with the current code and the above fix in `modules/default/newsfeed/newsfeedfetcher.js` solves the problem.

So will provide a PR for this.
