### ISSUE TITLE
Add CHANGELOG entry for dependabot PRs

### ISSUE THREAD

**Issue by rejas** [MagicMirrorOrg/MagicMirror#3320]
Currently our checks complain about the dependabot PRs since they dont add a CHANGELOG entry.

Maybe someone can look into https://github.com/dangoslen/dependabot-changelog-helper
and see if it can be used to turn the PR-checks green.

**Comment by khassel** [comment]
can take a look but do we really need this?

I'm fine with the one failing test and we can merge these PR's if all other tests are green.

I don't need every version update in the changelog, this will only blew up this file with unneeded things. For me it's o.k. to mention only significant updates as e.g. `electron` and have an entry `dependencies updated` for the normal updates (what we are doing already).

And I think we don't need this for the whole dev dependencies.

**Comment by khassel** [comment]
as an alternative approach we could add the label `Skip Changelog` to the `dependabot` PR's to avoid the failed tests.

**Comment by rejas** [comment]
> as an alternative approach we could add the label `Skip Changelog` to the `dependabot` PR's to avoid the failed tests.

I am totally fine with this approach

**Comment by khassel** [comment]
still not working, the `Skip Changelog` label is missing so check fails.

**Comment by rejas** [comment]
maybe the PR needs to find its way to master first?

**Comment by rejas** [comment]
I you want to, you can cherrypick it. I myself wouldnt mind  aiting for the next release branch.
