### ISSUE TITLE
emergency 2.26 package,json has an extra comma 

### ISSUE THREAD

**Issue by sdetweil** [MagicMirrorOrg/MagicMirror#3322]
```
		"module-alias": "^2.2.3",
```

fails json validation

**Comment by sdetweil** [comment]
not sure, part of file missing.. 

https://forum.magicmirror.builders/topic/18038/merge-conflict-detected-in-your-package-json/11?page=2

**Comment by khassel** [comment]
see no problems with `package.json`, the build of my docker images did work.

Can you reproduce this? Looks like local merge conflicts in the forum thread ...

**Comment by sdetweil** [comment]
waiting

**Comment by khassel** [comment]
I now cloned the repo and running `npm run install-mm` did work.

**Comment by KristjanESPERANTO** [comment]
I can't detect any problems either. Running 2.26 on Debian 12.

**Comment by sdetweil** [comment]
i checked as well.. seems a bad merge conflict correction... he is running from good package.json, closing
