### ISSUE TITLE
updatenotification  upgrade fails to check if Pm2 being used for MM.. 

### ISSUE THREAD

**Issue by sdetweil** [MagicMirrorOrg/MagicMirror#3324]
messages
```
[01.01.2024 12:52.41.557] [ERROR] updatenotification: [PM2] can't GetList!
[01.01.2024 12:52.41.557] [ERROR] updatenotification: [PM2] Can't get process List!
```
these is a misleading message

in my upgradepm2 script I check 
```
if [ $(pm2 ls -m | grep "\-\-" | grep -i magicmirror | wc -l) -eq 1 ]; then
```
one coudl also check the paths of the apps used to start the app

**Comment by bugsounet** [comment]
related to [this](https://github.com/MagicMirrorOrg/MagicMirror/pull/3285)

**Comment by sdetweil** [comment]
I know why. just reporting that you could handle it and not put out an erroneous error

**Comment by Pollard-J** [comment]
ive just updated my MM and now it doesnt launch? i do use the pm2 to launch it.

**Comment by sdetweil** [comment]
this has nothing to do with the issue.. 

anyhow do
```
pm2 stop all 
cd ~/MagicMirror
npm start 
```

dod you use my script or the manual install ?
did you install with my script?

**Comment by khassel** [comment]
is this still an issue or can we close this?

**Comment by bugsounet** [comment]
We can close it, solved by using pm2 dependency
