### ISSUE TITLE
Enlarge region for module

### ISSUE THREAD

**Issue by cschwarz007** [MagicMirrorOrg/MagicMirror#3334]
Dear all,

First: this is a really great product! I love my Magic Mirror. But I am struggling with my current use case: to display a camerafeed via iFrame (using module MMM-SmartWebDisplay).

Issue: only parts of the iFrame are shown and the region for the module does not resize dynamically. I first tried "fullscreen_below", expecting the iFrame would show on the bottom of the screen - this is not the case (it shows on top, but overlaying other content).

With "buttom_center" I get what you see in the picture - 300px wide only.

How do I resize the region for the module?

Many thanks!
Christian
![Screenshot 2024-01-05 105437](https://github.com/MagicMirrorOrg/MagicMirror/assets/20018714/549978ca-0ff8-4ba8-a80f-d2cecc7ccb91)

**Comment by sdetweil** [comment]
this really is a question for the module author and not a problem with MagicMirror.

 please open this issue on the SmartWebDisplay module GitHub page
or use the forums
