### ISSUE TITLE
Calendar Module: Not displaying all calendars.

### ISSUE THREAD

**Issue by GilmorHappy** [MagicMirrorOrg/MagicMirror#3372]
**Platform**: RPI3B rev1.2 Raspbian Bullseye

**Node Version**: v21.6.1

**MagicMirror² Version**: 2.26

**Description**: Calendar Module isn't showing all of my fetched calendars.

**Steps to Reproduce**: Restarting MM2 using pm2. Rarely the calendar is there. Mostly it's not.

**Expected Results**: US-Holiday, Trash Schedule, J's schedule and A's always appear. On both remote and local screen.

**Actual Results**: US-Holiday, Trash Schedule, J's schedule always appear. On local screen. A's schedule appears on local screen 25% of the time after reboot. A's schedule appears on a remove screen ~90% of the time.

**Configuration**: 

CONFIG BEFORE CALENDAR MODULE
                {
                        module: "calendar",
                        header: "Calendar",
                        position: "lower_third",
                        config: {
                                coloredSymbol: true,
                                maximumEntries: 15,
                                maxTitleLength: 50,
                                calendars:      [
                                                        {
                                                        //US-Holidays
                                                        fetchInterval: 86400000,
                                                        symbol: "calendar-check",
                                                        url: "https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics",
                                                        color: "#ffffff"
                                                        },
                                                        {
                                                        //Trash Schedule
                                                        fetchInterval: 86400000,
                                                        symbol: "trash-can",
                                                        url: "https://recollect.a.ssl.fastly.net/api/places/54766588-581B-11E6-9C6C-B45D0AD10A3C/services/319/events.en-US.ics?client_id=<privatestring>",
                                                        color: "#67a440"
                                                        },
                                                        {
                                                        //A's Schedule
                                                        fetchInterval: 300000,
                                                        symbol: "calendar",
                                                        url: "https://calendar.google.com/calendar/ical/<a's email>/private-<privitestring>/basic.ics",
                                                        color: "#ffc0cb"
                                                        },
                                                        {
                                                        //J's Schedule
                                                        fetchInterval: 300000,
                                                        symbol: "calendar",
                                                        url: "https://calendar.google.com/calendar/ical/<j's email>/private-<privatestring>/basic.ics",
                                                        color: "#6ca0dc"
                                                        }

                                                ]
                                }
                },
CONTINUED CONFIG AFTER CALENDAR MODULE

**Additional Notes**: This issue started to occur after I update to MM 2.25 or 2.26, and wasn't occuring before. I believe I was on 2.22 or 2.23 before updating.

**Comment by sdetweil** [comment]
install the old parser

```
cd MagicMirror
npm install node-ical@0.16.1
```
restart mm

**Comment by GilmorHappy** [comment]
Seems to be working great. Thanks for the simple fix.
