### ISSUE TITLE
Move Module MMM-awesome-alexa to abandoned modules

### ISSUE THREAD

**Issue by tfischer4765** [MagicMirrorOrg/MagicMirror#3398]
Module MMM-awesome-alexa hasn't had any commits, issues answered or the documentation updated in over a year. The documentation currently available does not work any more. 

I therefore suggest moving the module to the "abandoned" section.

**Comment by KristjanESPERANTO** [comment]
Done: https://github.com/MagicMirrorOrg/MagicMirror/wiki/3rd-Party-Modules/_compare/b1db6c08eb5397af23f0c3f1362cd70aebde8c56...c8bad463cf7ee244697adf5b095aa386b7d90ce5

**Comment by tfischer4765** [comment]
Thanks for helping out! I know I could edit it, but I'm a guest here and I am hesitant to stick my fingies into other people's business, potentially ignoring some established procedure and annoying people I may very well depend on very soon.
