### ISSUE TITLE
online documentation missing many config options for default modules

### ISSUE THREAD

**Issue by sdetweil** [MagicMirrorOrg/MagicMirror#3418]
trying to help user format calendar output, 
dateEndFormat is not listed anymore
showEnd.

etc

**Comment by rejas** [comment]
I see "dateEndFormat" on https://docs.magicmirror.builders/modules/calendar.html#configuration-options 
<img width="894" alt="grafik" src="https://github.com/MagicMirrorOrg/MagicMirror/assets/1313547/f957d016-46f2-46cc-bbf2-d93ff864b0e5">
your browser seems to be buggy, sam...

**Comment by sdetweil** [comment]
no.. it WAS NOT there... and then u pushed a new doc update and poof it was back ..

**Comment by rejas** [comment]
:-) glad to hear, so closing it now :-)
