### ISSUE TITLE
[weather] unit of config is not respected on broadcasted notifications

### ISSUE THREAD

**Issue by eouia** [MagicMirrorOrg/MagicMirror#3419]
**Platform**: All (Mainly tested on MacOS, RPI 4)

**Node Version**: 20.8.0

**MagicMirror² Version**: 2.27

**Description**: When the default weather module broadcasts its notification as `WEATHER_UPDATED`, the `imperial` units of current / forecasting temperatures (and speed of wind) is not respected. it is delivered as `metric` value.

**Steps to Reproduce**:
```js
/* config/config.js*/
units: "imperial",

modules: [
             {
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "..."
			}
		},
  ...
```
**Expected Results**: 
<img width="307" alt="image" src="https://github.com/MagicMirrorOrg/MagicMirror/assets/1720610/9cc57470-cec3-4837-ba7e-8ab58ecdf1f0">

**Actual Results**:

<img width="307" alt="image" src="https://github.com/MagicMirrorOrg/MagicMirror/assets/1720610/254ce972-9682-4bbb-95ac-c0ad6acc2a8b">

**Additional Notes**: I knew about this issue since very early MM, but nobody has reported this issue still yet. So I do.

**Comment by skpanagiotis** [comment]
Hello, I would like to contribute with a solution.

**Comment by sdetweil** [comment]
@skpanagiotis   ok, code it up and submit a pull request to be considered.

**Comment by skpanagiotis** [comment]
I have add this PR #3519 for the issue.
