### ISSUE TITLE
online doc initial page on android phone hamburger menu doesnt respond

### ISSUE THREAD

**Issue by sdetweil** [MagicMirrorOrg/MagicMirror#3420]
second page works ok

**Comment by rejas** [comment]
works for me when opening the docs on chrome. what browser are you using?

**Comment by sdetweil** [comment]
so I have narrowed this down to my new phone.. it is a samsung fold.  in single pane view it is ok
but on openm pane the left menu has no data

**Comment by sdetweil** [comment]
![Screenshot_20240420_150603_Chrome](https://github.com/MagicMirrorOrg/MagicMirror/assets/1498142/3fd2941c-9573-4b0f-bbd2-9922529032ba)

**Comment by sdetweil** [comment]
![Screenshot_20240420_150548_Chrome](https://github.com/MagicMirrorOrg/MagicMirror/assets/1498142/2b26d0f9-9486-41ff-a3d7-873c21f03259)

**Comment by rejas** [comment]
oh, you mean the forum, not the docs...

**Comment by sdetweil** [comment]
it also happened on the docs, but doesn't now..

**Comment by rejas** [comment]
good to hear that it works now
