### ISSUE TITLE
Crash on Start possibility

### ISSUE THREAD

**Issue by bugsounet** [MagicMirrorOrg/MagicMirror#3442]
I just see crash possibility:
* if `module:` is missing in module configuration object
* module configuration object is empty

crash return:
```
[2024-05-07 12:54:10.972] [ERROR] (node:18916) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'split')
    at loadModule (/home/bugsounet/MagicMirror/js/app.js:156:27)
    at loadModules (/home/bugsounet/MagicMirror/js/app.js:213:10)
    at async App.start (/home/bugsounet/MagicMirror/js/app.js:261:3)
(Use `electron --trace-warnings ...` to show where the warning was created) 
```

I will see to patch it

**Comment by sdetweil** [comment]
but a few modules in defaults don't have config object.. why now?

**Comment by sdetweil** [comment]
![Screenshot_20240507_070005_Chrome](https://github.com/MagicMirrorOrg/MagicMirror/assets/1498142/57a6c079-1b4a-48aa-b526-7d01c1f7e9ec)

**Comment by sdetweil** [comment]
oh..  

I thought you meant
```js
config:{}
```

**Comment by bugsounet** [comment]
should we correct this issue?

**Comment by sdetweil** [comment]
yes.. never crash

**Comment by bugsounet** [comment]
never crash, no issue about this,  so it's not needed ;)

**Comment by sdetweil** [comment]
I font understand.  we should never crash from users mistakes. 
so anytime we find one we should fix it. like this

yes it's needed to.prevent crash
