### ISSUE TITLE
Option to turn on/off monitor under certain conditions

### ISSUE THREAD

**Issue by Batcastle** [MagicMirrorOrg/MagicMirror#3469]
Title explains the idea. I want MagicMirror to run off the monitor when not in use. For instance:

Between the hours of 11:30PM and 6:30AM, the monitor should be off.

If a light sensor detects the light in the room is below a certain point, MagicMirror should turn off the monitor.

If facial/person recognition is setup, if no one is standing in front of the mirror after a period of time, the monitor should go blank/turn off.

The idea is to save power, and limit light emission when setup in a bedroom. Is something like this possible?

Thanks!

**Comment by rejas** [comment]
Hi, this is possible with a few modules that you can find here probably: https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/

Some motion detector modules are there that turnoff/on the screen. As for a time-based solution I dont have one from the top of my head, but shouldnt be too hard.
