### ISSUE TITLE
INFO: Website, no WWW? 

### ISSUE THREAD

**Issue by BKeyport** [MagicMirrorOrg/MagicMirror#3524]
Information: There appears to be no WWW alias on the website, is it possible to add it for consistency?

**Comment by sdetweil** [comment]
its not required anymore

**Comment by BKeyport** [comment]
I know it's not required, this is why I said "for consistency" -- it's still best practice.

**Comment by sdetweil** [comment]
i dont think its best practice anymore

**Comment by sdetweil** [comment]
![IMG_0133](https://github.com/user-attachments/assets/4688a7b6-3ea5-48b7-8510-58c2c28ccc4d)

**Comment by khassel** [comment]
I can add a redirect from www to non-www

**Comment by sdetweil** [comment]
I don't think this is necessary. the doc and all reference material, history doesn't use www., and it doesn't work (as expected)

**Comment by khassel** [comment]
> I don't think this is necessary

but it doesn't do any harm either so I added the redirect.

**Comment by sdetweil** [comment]
cool
