### ISSUE TITLE
Add warning message to MagicMirrorOS

### ISSUE THREAD

**Issue by tfischer4765** [MagicMirrorOrg/MagicMirror#3525]
MagicMirrorOS, while a cool idea, seems to be unmaintained and quite outdated, to the point where packages on the host system can't be updated easily without expert knowledge. 

A warning should be added to the installation method in https://docs.magicmirror.builders/getting-started/installation.html#magicmirroros to notify users of potential problems and security issues using it.

**Comment by sdetweil** [comment]
its not part of the base MagicMirror. 

its developed and owned by a user just
like you.

**Comment by tfischer4765** [comment]
The documentation I linked however IS owned and operated by the MagicMirror core team, is it not?

**Comment by sdetweil** [comment]
yes. in this case we should remove that entry.

**Comment by rejas** [comment]
> yes. in this case we should remove that entry.

I dont want to remove that useful information. As we already state on top of the paragraph:

"The following installation methods are not maintained by the MagicMirror² core team. Use these scripts and methods at your own risk."

Maybe its enough to put this into a yellow Attention Box to make it clearer?

**Comment by sdetweil** [comment]
i personally hate that sentence, "use at your own risk", given how much time i put into install and upgrade

**Comment by khassel** [comment]
> MagicMirrorOS, while a cool idea, seems to be unmaintained and quite outdated

it was updated ~2 weeks ago and uses actual raspian os lite images as base

**Comment by khassel** [comment]
@tfischer4765 

no feedback: I will close this
otherwise: I will move this to the documentation repo
