### ISSUE TITLE
[tests] electron-rebuild test fails with node v20.9.0

### ISSUE THREAD

**Issue by khassel** [MagicMirrorOrg/MagicMirror#3573]
Problem is `npm install drivelist`, see e.g. [this job log](https://github.com/MagicMirrorOrg/MagicMirror/actions/runs/11123546494/job/30907210732).

The above command succeeds with latest node versions v20 and v22 (tested this). It is not related to MagicMirror, I can create a new project with `npm install -y` and `npm install drivelist` fails.

@bugsounet any idea?

Options:
- remove this test for node v20.9.0
- remove `drivelist`
- replace `drivelist` with another package

**Comment by bugsounet** [comment]
Hi, i will inspect this evening
