### ISSUE TITLE
Npm run install-mm fails

### ISSUE THREAD

**Issue by michaeldun123** [MagicMirrorOrg/MagicMirror#3612]
## I found a bug in MagicMirror

Please make sure to only submit reproducible issues. You can safely remove everything above the dividing line.
When submitting a new issue, please supply the following information:

**Platform**: Ubuntu 24.04.1 LTS

**Node Version**: 23

**MagicMirror² Version**: 2.29.0

**Description**: Npm run install-mm fails

**Steps to Reproduce**: 
1: Git clone the repo
2: cd into the repo
3: run command

**Expected Results**: for it not to error out

**Actual Results**: 
> magicmirror@2.29.0 install-mm
> npm install --no-audit --no-fund --no-update-notifier --only=prod --omit=dev

(node:22741) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: magicmirror@2.29.0
npm error notsup Not compatible with your version of node/npm: magicmirror@2.29.0
npm error notsup Required: {"node":">=20.9.0 <21 || 22"}
npm error notsup Actual:   {"npm":"10.9.0","node":"v23.1.0"}
npm error A complete log of this run can be found in: /home/<username>/.npm/_logs/2024-10-31T17_25_41_188Z-debug-0.log

**Configuration**: This hasn't provided any config for me. This is the step before the new config

**Comment by michaeldun123** [comment]
This is the same case using @sdetweil 's installer 
![image](https://github.com/user-attachments/assets/975033ed-af45-4671-be29-0855b926bea8)

**Comment by sdetweil** [comment]
clearly you didn't read the documentation

**Comment by khassel** [comment]
from [release info for v2.29.0](https://github.com/MagicMirrorOrg/MagicMirror/releases/tag/v2.29.0):


    ⚠️ This release needs nodejs version v20 or v22, minimum version is v20.9.0

**Comment by sdetweil** [comment]
![IMG_0426](https://github.com/user-attachments/assets/ec2409ea-9e85-4408-a039-5f5ec11cd8c7)

**Comment by michaeldun123** [comment]
Doesn't say on that website that it requires that
