### ISSUE TITLE
linting/prettier not working anymore on `develop`

### ISSUE THREAD

**Issue by khassel** [MagicMirrorOrg/MagicMirror#3632]
see https://github.com/MagicMirrorOrg/MagicMirror/pull/3630 as example

I'm far away from this topic, what I found: With release `v2.26.0` `*.js` was added to `.prettierignore` so from this point on prettier is ignoring all js files.

Maybe @rejas @KristjanESPERANTO can look at this, thanks!

**Comment by KristjanESPERANTO** [comment]
I'm onto it.

**Comment by KristjanESPERANTO** [comment]
> linting/prettier not working anymore

The ignore pattern in the ESLint config caused the default modules to no longer be linted.

> *.js was added to .prettierignore so from this point on prettier is ignoring all js files.

Yes this was intended. Since we're using ESLint Stylistic to format the JavaScript code, we don't need to format these files with a second formatter (prettier).

PR #3633 should fix this.

**Comment by KristjanESPERANTO** [comment]
That was certainly my fault when I converted the deprecated ESLint config to flat config.

**Comment by khassel** [comment]
no problem, thanks for fixing, I didn't see it ...
